### ISSUE TITLE
你好，兄台项目做的很漂亮。在下想用用代码顺带做几件小事。

### ISSUE THREAD

**Issue by cupen** [ouqiang/supervisor-event-listener#3]
- [×] 构建方案改用 go module （兼容 gopath + vendor），方便 fork 在本地构建。
- [×] 发布改用 docker , 执行 make release 自动搞定.
- [×] 配置文件改用 toml 语法，代码层面就不必去手工解析，可以去掉一些 strings.trim 之类的代码。
- [×] 支持 bearychat 
- [×] 支持 feishu
- [×] 支持一个事件触发多个通知，比如可同时发到 slack 和 mail 等等，配置多少就发多少。
- [  ] 增加点 testcase，主要就写点 mock 类。回头改代码会放心一点，增加点心理舒适感。

**Comment by cupen** [comment]
toml 例子
```toml
# 邮件服务器配置
[mail]
user = "hello@163.com"
users = ["world@163.com", "world2@163.com"]
[mail.server]
user = "test@163.com"
password = "123456"
host = "smtp.163.com"
port = 25


# Slack配置
[slack]
webhook_url = "https://hooks.slack.com/services/xxxx/xxx/xxxx"
channel = "exception"

# Custom WebHook 
[webhook]
url = "http://my.webhook.com"


# BearyChat
[bearychat]
webhook_url = "https://hook.bearychat.com/=xxx/xxxxx/xxxx"
channel = "alert"
```
